version: '1.0'
services:
  sql_retail:
    image: postgres:latest
    container_name: retail
    ports: 
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retail
    volumes:
      - ./sql_scripts/ddl/1_ddl.sql:/docker-entrypoint-initdb.d/1_ddl.sql
      - ./sql_scripts/dml/2_dml.sql:/docker-entrypoint-initdb.d/2_dml.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always